apply plugin: 'java'

sourceCompatibility = '1.8'

[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'

//mainClassName = 'core.App'
version = '1.0.0'

repositories {
    mavenCentral()
    
    //allow local dependencies (dockframes)
    flatDir {
        dirs 'libs'
        dirs '../libs'
    }
}

dependencies {
    
    //Si arroja error al tratar de construir la aplicación, cambie "implementation" por "compile" o viceversa, ya que varía dependiendo de la versión de Gradle.
    
    //compile project(':mo')
    
    implementation name: "multimodal-observer", version: '0.0.0'
    implementation 'commons-io:commons-io:2.11.0'
    implementation 'bibliothek:docking-frames-core'
    implementation 'bibliothek:docking-frames-common'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.13.0'
    
    
    //compile project(':neurosky-mindwave-eeg-data')
    implementation name: "neurosky-mindwave-eeg-data", version: '0.0.0'
    
    testImplementation group: 'junit', name: 'junit', version: '4.10'

//    compile name: "docking-frames-core"
//    compile name: "docking-frames-common"
    //compile 'com.theeyetribe:eyetribe-java:0.9.60'
    /*
    // http://mvnrepository.com/artifact/commons-io/commons-io
    compile group: 'commons-io', name: 'commons-io', version: '2.5'

    //compile fileTree(dir: 'libs', include: '*.jar')
    //compile 'org.dockingframes:docking-frames-common:1.1.1'
    compile name: "docking-frames-core"
    compile name: "docking-frames-common"
    
    // http://mvnrepository.com/artifact/org.apache.commons/commons-configuration2
    compile group: 'org.apache.commons', name: 'commons-configuration2', version: '2.0'

    // http://mvnrepository.com/artifact/commons-beanutils/commons-beanutils
    compile group: 'commons-beanutils', name: 'commons-beanutils', version: '1.9.2'
    
    // https://mvnrepository.com/artifact/com.google.code.gson/gson
    compile group: 'com.google.code.gson', name: 'gson', version: '2.7'
    
    
       
    //Jackson: json lib
    // https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-core
    compile group: 'com.fasterxml.jackson.core', name: 'jackson-core', version: '2.8.5'
    // https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind
    compile group: 'com.fasterxml.jackson.core', name: 'jackson-databind', version: '2.8.5'*/
}

jar {
    manifest {
        attributes( 'Implementation-Title'   : 'Gradle',
                    'Implementation-Version' :  version,
                    'Main-Class': 'mo.eeg.capture.EEGCapturePlugin'
        )
    }
    
/*    from (configurations.compile.collect 
        { it.isDirectory() ? it : zipTree(it) }){
        // remove all signature files
        exclude "META-INF/*.SF"
        exclude "META-INF/*.DSA"
        exclude "META-INF/*.RSA"
    }*/
    
    doLast{
        project.file('build/libs/plugins').mkdirs()
        copy{
            from 'src/main/resources'
            into 'build/libs'
        }
    }
}
